### ISSUE TITLE
Add page to help with list of all keyboard shortcuts

### ISSUE THREAD

**Issue by erlloyd** [erlloyd/card-game-playground#74]

**Comment by Shevilll** [comment]
Can you explain this issue more precisely?

**Comment by phaufe** [comment]
Maybe add functionality to press "?" as a hotkey in the app , to then show an in app screen with keyboard shortcuts, which allows to go to the full documentary via link, just like github does it:

![image](https://user-images.githubusercontent.com/48793/235597068-e5c44614-6b04-4c40-94bf-93b1060617be.png)

**Comment by erlloyd** [comment]
This was added to the help documentation a bit ago: https://erlloyd.github.io/cardtable-docs/docs/keyboardshortcuts
